// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"yuxialuozi_graduation_design_backend/internal/config"
	"yuxialuozi_graduation_design_backend/internal/database"
	"yuxialuozi_graduation_design_backend/internal/handler"
	"yuxialuozi_graduation_design_backend/internal/repository"
	"yuxialuozi_graduation_design_backend/internal/router"
	"yuxialuozi_graduation_design_backend/internal/service"
)

func InitializeApp() (*router.Router, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	db, err := database.NewDatabase(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(db)
	authService := service.NewAuthService(userRepository, configConfig)
	authHandler := handler.NewAuthHandler(authService)
	tenantRepository := repository.NewTenantRepository(db)
	tenantService := service.NewTenantService(tenantRepository)
	tenantHandler := handler.NewTenantHandler(tenantService)
	contractRepository := repository.NewContractRepository(db)
	contractService := service.NewContractService(contractRepository, tenantRepository)
	contractHandler := handler.NewContractHandler(contractService)
	roomRepository := repository.NewRoomRepository(db)
	roomService := service.NewRoomService(roomRepository, tenantRepository)
	roomHandler := handler.NewRoomHandler(roomService)
	feeRepository := repository.NewFeeRepository(db)
	feeService := service.NewFeeService(feeRepository, tenantRepository)
	feeHandler := handler.NewFeeHandler(feeService)
	maintenanceRepository := repository.NewMaintenanceRepository(db)
	maintenanceService := service.NewMaintenanceService(maintenanceRepository, tenantRepository)
	maintenanceHandler := handler.NewMaintenanceHandler(maintenanceService)
	reportService := service.NewReportService(feeRepository, roomRepository, maintenanceRepository, tenantRepository, contractRepository)
	reportHandler := handler.NewReportHandler(reportService)
	routerRouter := router.NewRouter(configConfig, authHandler, tenantHandler, contractHandler, roomHandler, feeHandler, maintenanceHandler, reportHandler)

	cleanup := func() {}

	return routerRouter, cleanup, nil
}
